In [14]:
# Normalization ---> Using MinMaxScaling 
# Data Min_Value = 0, Max_Value = 1

In [15]:
# Play store --> diff-diff apps -> 1 app downloads 4.2k, 1 app downloads 2.3M, 1 app download 650 
# In this condition, if I apply any operation, then it will retrurn huge number 
# and we can not perfrom any visualization because it will create a zig-zag situation. 

# Office me employee salary --> 5k, 50k, 2 lakhs, 10 lakhs --> Data scale --> MinMazxScalling

In [16]:
import numpy as np 
import pandas as pd

In [17]:
df = pd.read_csv('covid_toy.csv')

In [18]:
df = df.dropna()

In [19]:
df = df.drop(columns='city')

In [20]:
df.head(2)

   age gender  fever cough has_covid
0   60   Male  103.0  Mild        No
1   27   Male  100.0  Mild       Yes

In [21]:
# Step-1 ::: Covert categorical data into numerical data

In [22]:
df['gender'] = df['gender'].map({'Male':1, 'Female':0})
df['cough'] = df['cough'].map({'Strong':1, 'Mild':0})
df['has_covid'] = df['has_covid'].map({'Yes':1, 'No':0})

In [23]:
df.head(2)

   age  gender  fever  cough  has_covid
0   60       1  103.0      0          0
1   27       1  100.0      0          1

In [24]:
x = df.drop(columns='has_covid')
y = df['has_covid']

In [25]:
from sklearn.model_selection import train_test_split

In [26]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=42)

In [27]:
np.round(x_train.describe(), 2)

         age  gender   fever  cough
count  72.00   72.00   72.00  72.00
mean   43.53    0.36  100.74   0.35
std    25.30    0.48    2.12   0.48
min     5.00    0.00   98.00   0.00
25%    19.75    0.00   99.00   0.00
50%    47.00    0.00  101.00   0.00
75%    65.25    1.00  102.25   1.00
max    83.00    1.00  104.00   1.00

In [28]:
from sklearn.preprocessing import MinMaxScaler

In [31]:
mm = MinMaxScaler()

In [32]:
x_train_mm = mm.fit_transform(x_train)

In [33]:
x_train_new = pd.DataFrame(x_train_mm, columns=x_train.columns)

In [34]:
np.round(x_train_new.describe(),2)

         age  gender  fever  cough
count  72.00   72.00  72.00  72.00
mean    0.49    0.36   0.46   0.35
std     0.32    0.48   0.35   0.48
min     0.00    0.00   0.00   0.00
25%     0.19    0.00   0.17   0.00
50%     0.54    0.00   0.50   0.00
75%     0.77    1.00   0.71   1.00
max     1.00    1.00   1.00   1.00