In [2]:
# Machine learning 
# data(50) ----> x(input data), y(target data)
# x ----> x_train, x_test 
# y ----> y_train, y_test 

# for machine training we will pass (x_train, y_train) 
# for machine testing (x_test)  ----> y_pred 

# 1+1=2
# 1+2=3
# 1+4=5
# 1+6=7
# 1+8=9
# 1+7=8

# x = (1+1,1+2,......1+7)
# y = (2,3,5,7,9,8)
# x_train = (1+1, 1+2, 1+4, 1+6)
# x_test = (1+7,1+8) 
# y_train = (2,3,5,7)
# y_test = (9,8)

In [3]:
import pandas as pd

In [5]:
df = pd.read_csv('covid_toy.csv')
df.head(3)

   age gender  fever cough     city has_covid
0   60   Male  103.0  Mild  Kolkata        No
1   27   Male  100.0  Mild    Delhi       Yes
2   42   Male  101.0  Mild    Delhi        No

In [6]:
df.shape

(100, 6)

In [8]:
df.isnull().sum()

age           0
gender        0
fever        10
cough         0
city          0
has_covid     0
dtype: int64

In [9]:
df['fever'] = df['fever'].fillna(df['fever'].mean())

In [11]:
df.isnull().sum()

age          0
gender       0
fever        0
cough        0
city         0
has_covid    0
dtype: int64

In [15]:
x = df.drop(columns=['has_covid']) # input data 
x.head(3)

   age gender  fever cough     city
0   60   Male  103.0  Mild  Kolkata
1   27   Male  100.0  Mild    Delhi
2   42   Male  101.0  Mild    Delhi

In [21]:
y = df['has_covid']   #Target data
y.head(3)

0     No
1    Yes
2     No
Name: has_covid, dtype: object

In [22]:
from sklearn.model_selection import train_test_split

In [23]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=42)

In [24]:
print('Total Data Shape :', df.shape)
print('===================')
print('Input Data Shape :', x.shape)
print('x_train Data Shape :', x_train.shape)
print('x_test Data Shape :', x_test.shape)
print('===================')
print('Target Data Shape :', y.shape)
print('y_train Data Shape :', y_train.shape)
print('y_test Data Shape :', y_test.shape)

Total Data Shape : (100, 6)
===================
Input Data Shape : (100, 5)
x_train Data Shape : (80, 5)
x_test Data Shape : (20, 5)
===================
Target Data Shape : (100,)
y_train Data Shape : (80,)
y_test Data Shape : (20,)