In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('placement - placement.csv')
df.head(3)

   cgpa  resume_score  placed
0  8.14          6.52       1
1  6.17          5.17       0
2  8.27          8.86       1

In [3]:
x = df.drop(columns=['placed'])
x

    cgpa  resume_score
0   8.14          6.52
1   6.17          5.17
2   8.27          8.86
3   6.88          7.27
4   7.52          7.30
..   ...           ...
95  6.33          6.38
96  8.23          7.76
97  6.65          7.78
98  8.14          5.63
99  6.09          6.61

[100 rows x 2 columns]

In [5]:
y = df['placed']
y

0     1
1     0
2     1
3     1
4     1
     ..
95    0
96    1
97    0
98    1
99    0
Name: placed, Length: 100, dtype: int64

In [7]:
from sklearn.model_selection import train_test_split

In [8]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=42)

In [9]:
print('Total Data Shape :', df.shape)
print('===================')
print('Input Data Shape :', x.shape)
print('x_train Data Shape :', x_train.shape)
print('x_test Data Shape :', x_test.shape)
print('===================')
print('Target Data Shape :', y.shape)
print('y_train Data Shape :', y_train.shape)
print('y_test Data Shape :', y_test.shape)

Total Data Shape : (100, 3)
===================
Input Data Shape : (100, 2)
x_train Data Shape : (80, 2)
x_test Data Shape : (20, 2)
===================
Target Data Shape : (100,)
y_train Data Shape : (80,)
y_test Data Shape : (20,)