In [164]:
import numpy as np 
import pandas as pd

In [165]:
df = pd.read_csv('Churn_Modelling - Churn_Modelling.csv')
df.drop(columns=['Surname'], inplace=True)
df.head(3)

,RowNumber,CustomerId,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,3,15619304,502,France,Female,42,8,159660.80,3,1,0,113931.57,1

In [166]:
df.shape

(10000, 13)

In [167]:
df.isnull().sum()

RowNumber          0
CustomerId         0
CreditScore        0
Geography          0
Gender             0
Age                0
Tenure             0
Balance            0
NumOfProducts      0
HasCrCard          0
IsActiveMember     0
EstimatedSalary    0
Exited             0
dtype: int64

In [168]:
df['Geography'].value_counts()

Geography
France     5014
Germany    2509
Spain      2477
Name: count, dtype: int64

In [169]:
df['Gender'].value_counts()

Gender
Male      5457
Female    4543
Name: count, dtype: int64

### Label Encoding

In [170]:
from sklearn.preprocessing import LabelEncoder

In [171]:
le = LabelEncoder()

In [172]:
df['Geography'] = le.fit_transform(df['Geography'])
df['Gender'] = le.fit_transform(df['Gender'])

In [173]:
df.head(3)

,RowNumber,CustomerId,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,619,0,0,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,608,2,0,41,1,83807.86,1,0,1,112542.58,0
2,3,15619304,502,0,0,42,8,159660.80,3,1,0,113931.57,1

### Ordinal Encoding

In [174]:
df1 = pd.read_csv('Churn_Modelling - Churn_Modelling.csv')
df1.drop(columns=['Surname'], inplace=True)
df1.head(3)

,RowNumber,CustomerId,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,3,15619304,502,France,Female,42,8,159660.80,3,1,0,113931.57,1

In [175]:
from sklearn.preprocessing import OrdinalEncoder

In [176]:
oe = OrdinalEncoder(categories=[['France', 'Germany', 'Spain'], ['Male', 'Female']])

In [177]:
oe_ar = oe.fit_transform(df1[['Geography', 'Gender']])
oe_ar

array([[0., 1.],
       [2., 1.],
       [0., 1.],
       ...,
       [0., 1.],
       [1., 0.],
       [0., 1.]])

In [178]:
oe_df1 = pd.DataFrame(oe_ar, columns=df1[['Geography', 'Gender']].columns)
oe_df1.head(2)

   Geography  Gender
0        0.0     1.0
1        2.0     1.0

In [179]:
df1[['Geography', 'Gender']] = oe_df1
df1.head(2)

,RowNumber,CustomerId,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,619,0.0,1.0,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,608,2.0,1.0,41,1,83807.86,1,0,1,112542.58,0

### get_dummies

In [180]:
df2 = pd.read_csv('Churn_Modelling - Churn_Modelling.csv')
df2.drop(columns=['Surname'], inplace=True)
df2.head(3)

,RowNumber,CustomerId,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,3,15619304,502,France,Female,42,8,159660.80,3,1,0,113931.57,1

In [235]:
a = pd.get_dummies(df2,columns=['Geography', 'Gender'], drop_first=True, dtype=int)

In [236]:
a.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 14 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   RowNumber          10000 non-null  int64
 1   CustomerId         10000 non-null  int64
 2   CreditScore        10000 non-null  int64
 3   Age                10000 non-null  int64
 4   Tenure             10000 non-null  int64
 5   Balance            10000 non-null  float64
 6   NumOfProducts      10000 non-null  int64
 7   HasCrCard          10000 non-null  int64
 8   IsActiveMember     10000 non-null  int64
 9   EstimatedSalary    10000 non-null  float64
 10  Exited             10000 non-null  int64
 11  Geography_Germany  10000 non-null  int64
 12  Geography_Spain    10000 non-null  int64
 13  Gender_Male        10000 non-null  int64
dtypes: float64(2), int64(12)
memory usage: 1.1 MB

### OneHotEncoding

In [183]:
df3 = pd.read_csv('Churn_Modelling - Churn_Modelling.csv')
df3.drop(columns=['Surname'], inplace=True)
df3.head(3)

,RowNumber,CustomerId,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,3,15619304,502,France,Female,42,8,159660.80,3,1,0,113931.57,1

In [184]:
from sklearn.preprocessing import OneHotEncoder

In [185]:
ohe = OneHotEncoder(drop='first', sparse_output=False, dtype=np.int32)

In [186]:
ohe_ar = ohe.fit_transform(df[['Geography', 'Gender']])

In [187]:
ohe_ar

array([[0, 0, 0],
       [0, 1, 0],
       [0, 0, 0],
       ...,
       [0, 0, 0],
       [1, 0, 1],
       [0, 0, 0]], dtype=int32)

### Standardization

In [217]:
df.head(3)

,RowNumber,CustomerId,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,619,0,0,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,608,2,0,41,1,83807.86,1,0,1,112542.58,0
2,3,15619304,502,0,0,42,8,159660.80,3,1,0,113931.57,1

In [218]:
x = df.drop(columns='Exited')
y = df['Exited']

In [219]:
from sklearn.model_selection import train_test_split

In [220]:
x_train, x_test, y_train, y_test = train_test_split(x, y,test_size=0.20, random_state=42)

In [221]:
np.round(x_train.describe(), 2)

,RowNumber,CustomerId,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary
count,8000.00,8000.00,8000.00,8000.00,8000.00,8000.00,8000.00,8000.00,8000.00,8000.00,8000.00,8000.00
mean,5012.51,15690665.10,651.65,0.75,0.55,38.90,5.00,76102.14,1.53,0.70,0.51,100431.29
std,2887.65,71847.43,96.37,0.83,0.50,10.52,2.88,62461.01,0.58,0.46,0.50,57518.92
min,2.00,15565701.00,350.00,0.00,0.00,18.00,0.00,0.00,1.00,0.00,0.00,90.07
25%,2512.75,15628215.50,585.00,0.00,0.00,32.00,3.00,0.00,1.00,0.00,0.00,51364.12
50%,5014.50,15690738.00,653.00,1.00,1.00,37.00,5.00,96447.52,1.00,1.00,1.00,100487.72
75%,7505.25,15753164.25,719.00,1.00,1.00,44.00,7.00,127611.33,2.00,1.00,1.00,149595.84
max,10000.00,15815660.00,850.00,2.00,1.00,92.00,10.00,250898.09,4.00,1.00,1.00,199970.74

In [222]:
from sklearn.preprocessing import StandardScaler

In [223]:
sc = StandardScaler()

In [224]:
x_train_sc = sc.fit_transform(x_train)

In [226]:
# x_train_sc

In [227]:
new_x_train = pd.DataFrame(x_train_sc, columns=x.columns)

In [228]:
np.round(new_x_train.describe(), 2)

,RowNumber,CustomerId,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary
count,8000.00,8000.00,8000.00,8000.00,8000.00,8000.00,8000.00,8000.00,8000.00,8000.00,8000.00,8000.00
mean,-0.00,0.00,0.00,-0.00,0.00,-0.00,0.00,-0.00,0.00,-0.00,-0.00,0.00
std,1.00,1.00,1.00,1.00,1.00,1.00,1.00,1.00,1.00,1.00,1.00,1.00
min,-1.74,-1.74,-3.13,-0.91,-1.09,-1.99,-1.74,-1.22,-0.92,-1.54,-1.03,-1.74
25%,-0.87,-0.87,-0.69,-0.91,-1.09,-0.66,-0.70,-1.22,-0.92,-1.54,-1.03,-0.85
50%,0.00,0.00,0.01,0.30,0.91,-0.18,-0.00,0.33,-0.92,0.65,0.97,0.00
75%,0.86,0.87,0.70,0.30,0.91,0.49,0.69,0.82,0.81,0.65,0.97,0.85
max,1.73,1.74,2.06,1.51,0.91,5.05,1.73,2.80,4.26,0.65,0.97,1.73

### minmaxScalling

In [197]:
x = df1.drop(columns='Exited')
y = df1['Exited']

In [198]:
from sklearn.model_selection import train_test_split

In [199]:
x_train, x_test, y_train, y_test = train_test_split(x, y,test_size=0.20, random_state=42)

In [200]:
np.round(x_train.describe(), 2)

,RowNumber,CustomerId,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary
count,8000.00,8000.00,8000.00,8000.00,8000.00,8000.00,8000.00,8000.00,8000.00,8000.00,8000.00,8000.00
mean,5012.51,15690665.10,651.65,0.75,0.45,38.90,5.00,76102.14,1.53,0.70,0.51,100431.29
std,2887.65,71847.43,96.37,0.83,0.50,10.52,2.88,62461.01,0.58,0.46,0.50,57518.92
min,2.00,15565701.00,350.00,0.00,0.00,18.00,0.00,0.00,1.00,0.00,0.00,90.07
25%,2512.75,15628215.50,585.00,0.00,0.00,32.00,3.00,0.00,1.00,0.00,0.00,51364.12
50%,5014.50,15690738.00,653.00,1.00,0.00,37.00,5.00,96447.52,1.00,1.00,1.00,100487.72
75%,7505.25,15753164.25,719.00,1.00,1.00,44.00,7.00,127611.33,2.00,1.00,1.00,149595.84
max,10000.00,15815660.00,850.00,2.00,1.00,92.00,10.00,250898.09,4.00,1.00,1.00,199970.74

In [201]:
from sklearn.preprocessing import MinMaxScaler

In [202]:
mm = MinMaxScaler()

In [203]:
x_train_mm = mm.fit_transform(x_train)

In [204]:
x_train_new = pd.DataFrame(x_train_mm, columns=x_train.columns)

In [205]:
np.round(x_train_new.describe(),2)

,RowNumber,CustomerId,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary
count,8000.00,8000.00,8000.00,8000.00,8000.00,8000.00,8000.00,8000.00,8000.00,8000.00,8000.00,8000.00
mean,0.50,0.50,0.60,0.38,0.45,0.28,0.50,0.30,0.18,0.70,0.51,0.50
std,0.29,0.29,0.19,0.41,0.50,0.14,0.29,0.25,0.19,0.46,0.50,0.29
min,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
25%,0.25,0.25,0.47,0.00,0.00,0.19,0.30,0.00,0.00,0.00,0.00,0.26
50%,0.50,0.50,0.61,0.50,0.00,0.26,0.50,0.38,0.00,1.00,1.00,0.50
75%,0.75,0.75,0.74,0.50,1.00,0.35,0.70,0.51,0.33,1.00,1.00,0.75
max,1.00,1.00,1.00,1.00,1.00,1.00,1.00,1.00,1.00,1.00,1.00,1.00

In [ ]:
print