In [77]:
import numpy as np
import pandas as pd

from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split

from sklearn.linear_model import LinearRegression, Ridge, Lasso, ElasticNet
from sklearn.metrics import r2_score

In [53]:
df = pd.read_csv("/content/insurance - insurance.csv")

In [54]:
df.head(5)

   age     sex     bmi  children smoker     region      charges
0   19  female  27.900         0    yes  southwest  16884.92400
1   18    male  33.770         1     no  southeast   1725.55230
2   28    male  33.000         3     no  southeast   4449.46200
3   33    male  22.705         0     no  northwest  21984.47061
4   32    male  28.880         0     no  northwest   3866.85520

In [55]:
df.isnull().sum()

age         0
sex         0
bmi         0
children    0
smoker      0
region      0
charges     0
dtype: int64

In [56]:
df.shape

(1338, 7)

In [57]:
df.dropna(inplace=True)

In [58]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1338 entries, 0 to 1337
Data columns (total 7 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   age       1338 non-null   int64
 1   sex       1338 non-null   object
 2   bmi       1338 non-null   float64
 3   children  1338 non-null   int64
 4   smoker    1338 non-null   object
 5   region    1338 non-null   object
 6   charges   1338 non-null   float64
dtypes: float64(2), int64(2), object(3)
memory usage: 73.3+ KB

In [59]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()

In [60]:
cat = df.select_dtypes(include="object")

In [61]:
for i in cat:
  df[i] = le.fit_transform(df[i])

In [62]:
df.head()

   age  sex     bmi  children  smoker  region      charges
0   19    0  27.900         0       1       3  16884.92400
1   18    1  33.770         1       0       2   1725.55230
2   28    1  33.000         3       0       2   4449.46200
3   33    1  22.705         0       0       1  21984.47061
4   32    1  28.880         0       0       1   3866.85520

In [63]:

x = df.drop(columns=["charges"])
y = df["charges"]

In [64]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()

In [65]:
x_train, x_test, y_train, y_test = train_test_split(x, y,
                                                    test_size=0.20,
                                                    random_state=42)

In [81]:
models = {
    "lr" : LinearRegression(),
    "ridge" : Ridge(alpha=1.0),
    "Lasso" : Lasso(alpha=0.1),
    "Elasticnet" : ElasticNet(alpha=0.1, l1_ratio=0.5)
}

In [82]:
for name, model in models.items():
  model.fit(x_train, y_train)

  y_pred = model.predict(x_test)
  print(name, " : ", r2_score(y_test, y_pred))

lr  :  0.7833463107364539
ridge  :  0.78308491263913
Lasso  :  0.7833436574797585
Elasticnet  :  0.7411089508263367