In [90]:
import mysql.connector
import pandas as pd
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import OneHotEncoder
from sklearn.preprocessing import OrdinalEncoder
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import MinMaxScaler

In [91]:
conn = mysql.connector.connect(
    host="localhost", 
    user="root", 
    password="mr.abhi1149", 
    database="python_db"
)

In [92]:
q = "select * from tips_dataset"

In [93]:
df = pd.read_sql(q, conn)
df.head()

C:\Users\pc\AppData\Local\Temp\ipykernel_6440\873776951.py:1: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql(q, conn)

   total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

In [94]:
df.isnull().sum()

total_bill    0
tip           0
sex           0
smoker        0
day           0
time          0
size          0
dtype: int64

In [95]:
df.duplicated().sum()

np.int64(1)

In [96]:
df.drop_duplicates(inplace=True)

In [97]:
df.info()

<class 'pandas.DataFrame'>
Index: 243 entries, 0 to 243
Data columns (total 7 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   total_bill  243 non-null    float64
 1   tip         243 non-null    float64
 2   sex         243 non-null    str
 3   smoker      243 non-null    str
 4   day         243 non-null    str
 5   time        243 non-null    str
 6   size        243 non-null    int64
dtypes: float64(2), int64(1), str(4)
memory usage: 15.2 KB

# Label Encoding

In [98]:
cat_col = df.select_dtypes(include=str)

In [99]:
le = LabelEncoder()

In [100]:
for i in cat_col:
    df[i] = le.fit_transform(df[i])

In [101]:
df.head()

   total_bill   tip  sex  smoker  day  time  size
0       16.99  1.01    0       0    2     0     2
1       10.34  1.66    1       0    2     0     3
2       21.01  3.50    1       0    2     0     3
3       23.68  3.31    1       0    2     0     2
4       24.59  3.61    0       0    2     0     4

# OneHotEncoding

In [102]:
df1 = pd.read_sql(q, conn)
df1.head()

C:\Users\pc\AppData\Local\Temp\ipykernel_6440\1971796400.py:1: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df1 = pd.read_sql(q, conn)

   total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

In [103]:
ohe = OneHotEncoder(sparse_output=False, drop='first')

In [104]:
df1 = ohe.fit_transform(df1)

In [105]:
df1

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]], shape=(244, 361))

# Ordinal Encoding

In [106]:
df2 = pd.read_sql(q, conn)
df2.head()

C:\Users\pc\AppData\Local\Temp\ipykernel_6440\23752882.py:1: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df2 = pd.read_sql(q, conn)

   total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

In [107]:
df2['time'].value_counts()

time
Dinner    176
Lunch      68
Name: count, dtype: int64

In [108]:
oe = OrdinalEncoder(categories=[['Female', 'Male'], ['No', 'Yes'], ['Lunch', 'Dinner']])

df2_oe_ar = oe.fit_transform(df2[['sex', 'smoker', 'time']])

In [109]:
df2_oe_ar

array([[0., 0., 1.],
       [1., 0., 1.],
       [1., 0., 1.],
       [1., 0., 1.],
       [0., 0., 1.],
       [1., 0., 1.],
       [1., 0., 1.],
       [1., 0., 1.],
       [1., 0., 1.],
       [1., 0., 1.],
       [1., 0., 1.],
       [0., 0., 1.],
       [1., 0., 1.],
       [1., 0., 1.],
       [0., 0., 1.],
       [1., 0., 1.],
       [0., 0., 1.],
       [1., 0., 1.],
       [0., 0., 1.],
       [1., 0., 1.],
       [1., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [1., 0., 1.],
       [1., 0., 1.],
       [1., 0., 1.],
       [1., 0., 1.],
       [1., 0., 1.],
       [1., 0., 1.],
       [0., 0., 1.],
       [1., 0., 1.],
       [1., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [1., 0., 1.],
       [1., 0., 1.],
       [1., 0., 1.],
       [0., 0., 1.],
       [1., 0., 1.],
       [1., 0., 1.],
       [1., 0., 1.],
       [1., 0., 1.],
       [1., 0., 1.],
       [1., 0., 1.],
       [1., 0., 1.],
       [1., 0., 1.],
       [1., 0., 1.],
       [1., 0., 1.],
       [1., 0., 1.],
       [1., 0., 1.],
       [1., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [1., 0., 1.],
       [1., 0., 1.],
       [1., 0., 1.],
       [1., 1., 1.],
       [0., 0., 1.],
       [1., 1., 1.],
       [1., 0., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 0., 1.],
       [1., 0., 1.],
       [0., 0., 1.],
       [0., 1., 1.],
       [1., 0., 1.],
       [1., 1., 1.],
       [1., 0., 1.],
       [0., 0., 1.],
       [0., 1., 1.],
       [0., 1., 1.],
       [0., 0., 1.],
       [1., 0., 1.],
       [1., 1., 1.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 1., 0.],
       [1., 0., 0.],
       [0., 0., 0.],
       [1., 1., 0.],
       [1., 0., 0.],
       [0., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 1., 1.],
       [1., 0., 1.],
       [0., 1., 1.],
       [0., 1., 1.],
       [0., 0., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 0., 1.],
       [0., 1., 1.],
       [0., 1., 1.],
       [0., 1., 1.],
       [0., 1., 1.],
       [0., 0., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 0., 1.],
       [0., 1., 1.],
       [1., 0., 1.],
       [0., 0., 1.],
       [1., 0., 1.],
       [1., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [1., 0., 1.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [1., 0., 0.],
       [0., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [1., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [1., 1., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 1.],
       [1., 0., 1.],
       [1., 0., 1.],
       [1., 0., 1.],
       [1., 0., 1.],
       [0., 0., 1.],
       [1., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [1., 0., 1.],
       [1., 0., 1.],
       [1., 0., 1.],
       [0., 0., 1.],
       [1., 0., 1.],
       [0., 1., 1.],
       [1., 0., 1.],
       [1., 0., 1.],
       [1., 0., 1.],
       [0., 1., 1.],
       [0., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [0., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 0., 1.],
       [0., 1., 1.],
       [1., 1., 1.],
       [0., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [0., 1., 0.],
       [1., 1., 0.],
       [1., 1., 0.],
       [1., 1., 0.],
       [1., 0., 0.],
       [1., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [1., 1., 0.],
       [1., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [1., 1., 0.],
       [0., 1., 0.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [0., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 0., 1.],
       [0., 1., 1.],
       [0., 1., 1.],
       [0., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [0., 1., 1.],
       [1., 1., 0.],
       [0., 1., 0.],
       [1., 1., 0.],
       [0., 0., 0.],
       [1., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [1., 0., 1.],
       [1., 0., 1.],
       [0., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 0., 1.],
       [1., 0., 1.],
       [1., 1., 1.],
       [1., 0., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [0., 0., 1.],
       [1., 0., 1.],
       [0., 1., 1.],
       [1., 1., 1.],
       [1., 0., 1.],
       [0., 0., 1.]])

# pd.getdummies

In [150]:
df3 = pd.read_sql(q, conn)
df3.head()

C:\Users\pc\AppData\Local\Temp\ipykernel_6440\475808437.py:1: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df3 = pd.read_sql(q, conn)

   total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

In [152]:
pd.get_dummies(df3, drop_first=False, dtype=None)

,total_bill,tip,size,sex_Female,sex_Male,smoker_No,smoker_Yes,day_Fri,day_Sat,day_Sun,day_Thur,time_Dinner,time_Lunch
0,16.99,1.01,2,True,False,True,False,False,False,True,False,True,False
1,10.34,1.66,3,False,True,True,False,False,False,True,False,True,False
2,21.01,3.50,3,False,True,True,False,False,False,True,False,True,False
3,23.68,3.31,2,False,True,True,False,False,False,True,False,True,False
4,24.59,3.61,4,True,False,True,False,False,False,True,False,True,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...
239,29.03,5.92,3,False,True,True,False,False,True,False,False,True,False
240,27.18,2.00,2,True,False,False,True,False,True,False,False,True,False
241,22.67,2.00,2,False,True,False,True,False,True,False,False,True,False
242,17.82,1.75,2,False,True,True,False,False,True,False,False,True,False
243,18.78,3.00,2,True,False,True,False,False,False,False,True,True,False

# Data Dividation

In [110]:
x = df.drop(columns='total_bill')
y = df['total_bill']

In [111]:
x_train, x_test, y_train, y_test = train_test_split(x,y, test_size=0.20, random_state=42)
x_train1, x_test1, y_train1, y_test1 = train_test_split(x,y, test_size=0.20, random_state=42)

# Standardization

In [112]:
sc = StandardScaler()

In [113]:
x_train_scaled = sc.fit_transform(x_train) 
x_test_scaled = sc.fit(x_test)

In [114]:
x_train_scaled_df = pd.DataFrame(x_train_scaled, columns=x_train.columns)

In [115]:
x_train_scaled_df.describe()

,tip,sex,smoker,day,time,size
count,1.940000e+02,1.940000e+02,1.940000e+02,1.940000e+02,1.940000e+02,1.940000e+02
mean,2.289120e-16,4.578239e-17,9.156479e-17,8.698655e-17,-6.409535e-17,-8.698655e-17
std,1.002587e+00,1.002587e+00,1.002587e+00,1.002587e+00,1.002587e+00,1.002587e+00
min,-1.528662e+00,-1.301708e+00,-8.112457e-01,-1.853296e+00,-6.691496e-01,-1.684186e+00
25%,-7.774769e-01,-1.301708e+00,-8.112457e-01,-8.050762e-01,-6.691496e-01,-6.302114e-01
50%,-2.629149e-02,7.682213e-01,-8.112457e-01,2.431438e-01,-6.691496e-01,-6.302114e-01
75%,4.150299e-01,7.682213e-01,1.232672e+00,1.291364e+00,1.494434e+00,4.237629e-01
max,4.480821e+00,7.682213e-01,1.232672e+00,1.291364e+00,1.494434e+00,3.585686e+00

# MinMaxScaler

In [116]:
ms = MinMaxScaler()

In [117]:
x_train_scaled = sc.fit_transform(x_train1) 
x_test_scaled = sc.fit(x_test1)

In [118]:
x_train_scaled_df = pd.DataFrame(x_train_scaled, columns=x_train.columns)

In [119]:
x_train_scaled_df.describe()

,tip,sex,smoker,day,time,size
count,1.940000e+02,1.940000e+02,1.940000e+02,1.940000e+02,1.940000e+02,1.940000e+02
mean,2.289120e-16,4.578239e-17,9.156479e-17,8.698655e-17,-6.409535e-17,-8.698655e-17
std,1.002587e+00,1.002587e+00,1.002587e+00,1.002587e+00,1.002587e+00,1.002587e+00
min,-1.528662e+00,-1.301708e+00,-8.112457e-01,-1.853296e+00,-6.691496e-01,-1.684186e+00
25%,-7.774769e-01,-1.301708e+00,-8.112457e-01,-8.050762e-01,-6.691496e-01,-6.302114e-01
50%,-2.629149e-02,7.682213e-01,-8.112457e-01,2.431438e-01,-6.691496e-01,-6.302114e-01
75%,4.150299e-01,7.682213e-01,1.232672e+00,1.291364e+00,1.494434e+00,4.237629e-01
max,4.480821e+00,7.682213e-01,1.232672e+00,1.291364e+00,1.494434e+00,3.585686e+00