In [83]:
import pymysql
import pandas as pd 
import numpy as np

In [84]:
df = pd.read_csv("Churn_Modelling - Churn_Modelling.csv")
df.head(5)

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,4,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,5,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0

In [85]:
conn = pymysql.connect(
    host="localhost",
    user="root",
    password="mr.abhi1149",
    database="python_db"
)

In [86]:
df = pd.read_sql("SELECT * FROM churn_modelling", conn)
df.head()

C:\Users\pc\AppData\Local\Temp\ipykernel_3884\671088874.py:1: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql("SELECT * FROM churn_modelling", conn)

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,4,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,5,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0

In [87]:
df.drop(columns=['Surname'], inplace=True)

In [88]:
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import OneHotEncoder 
from sklearn.model_selection import train_test_split
from sklearn.compose import ColumnTransformer

In [89]:
x_train, x_test, y_train, y_test = train_test_split(df.drop(columns=['Exited']), df['Exited'], random_state=42, test_size=0.20)

In [90]:
transformer = ColumnTransformer(transformers=[
    ('trf1', OneHotEncoder(sparse_output=False, drop='first'), ['Geography', 'Gender']), 
    ('trf2', StandardScaler(), x_train.drop(columns=['Geography', 'Gender']).columns)
], remainder='passthrough')

In [91]:
x_train_trans = transformer.fit_transform(x_train)

In [95]:
feature_names = transformer.get_feature_names_out()
clean_names = [name.split('__')[1] for name in feature_names]
# trf1__Geography_Germany -> ['trf1', 'Geography_Germany']
x_train_new = pd.DataFrame(x_train_trans, columns=clean_names)

In [96]:
x_train_new.describe()

,Geography_Germany,Geography_Spain,Gender_Male,RowNumber,CustomerId,CreditScore,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary
count,8000.000000,8000.000000,8000.000000,8.000000e+03,8.000000e+03,8.000000e+03,8.000000e+03,8.000000e+03,8.000000e+03,8.000000e+03,8.000000e+03,8.000000e+03,8.000000e+03
mean,0.251375,0.249375,0.545250,-1.598721e-17,6.219913e-15,5.435652e-16,-1.896261e-16,6.661338e-17,-3.099743e-16,1.065814e-16,-3.197442e-17,-1.776357e-17,1.776357e-17
std,0.433831,0.432678,0.497979,1.000063e+00,1.000063e+00,1.000063e+00,1.000063e+00,1.000063e+00,1.000063e+00,1.000063e+00,1.000063e+00,1.000063e+00,1.000063e+00
min,0.000000,0.000000,0.000000,-1.735259e+00,-1.739407e+00,-3.130418e+00,-1.986800e+00,-1.736467e+00,-1.218471e+00,-9.166877e-01,-1.540351e+00,-1.025834e+00,-1.744600e+00
25%,0.000000,0.000000,0.000000,-8.657260e-01,-8.692517e-01,-6.916511e-01,-6.557859e-01,-6.953935e-01,-1.218471e+00,-9.166877e-01,-1.540351e+00,-1.025834e+00,-8.531146e-01
50%,0.000000,0.000000,1.000000,6.902672e-04,1.014740e-03,1.403458e-02,-1.804237e-01,-1.344719e-03,3.257497e-01,-9.166877e-01,6.492027e-01,9.748170e-01,9.811339e-04
75%,1.000000,0.000000,1.000000,8.632970e-01,8.699414e-01,6.989648e-01,4.850833e-01,6.927040e-01,8.247131e-01,8.084362e-01,6.492027e-01,9.748170e-01,8.548079e-01
max,1.000000,1.000000,1.000000,1.727289e+00,1.739835e+00,2.058448e+00,5.048560e+00,1.733777e+00,2.798656e+00,4.258684e+00,6.492027e-01,9.748170e-01,1.730660e+00

In [98]:
# churn modelling dataset --->
#  database connectivity ---> 
# fectch the data --->
#  aply encoding and Standardization